name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-docker-image .

      # Run Docker container
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-container my-docker-image
