name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up -d --build app

      - name: Install npm packages
        run: |
          echo 'NPM INSTALL'
          docker-compose exec app npm install 
          echo 'INSTALLING DEPENDENCIES WITH APT'
          docker-compose exec app apt-get update && apt-get install -y python3 make g++ gcc
          echo 'NPM LIST'
          docker-compose exec app npm list


      - name: Run Tests
        run: |
          docker-compose exec app npm run test src/__tests__/query.test.ts 

      - name: Tear Down
        if: always()
        run: |
          docker-compose down
