name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up -d --build

      - name: Run Tests
        run: |
          docker-compose exec app npm run test src/__tests__/query.test.ts  # Replace with your test command

      - name: Tear Down
        if: always()
        run: |
          docker-compose down
