name: Docker Compose Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up app -d --build

      - name: Run Tests
        run: |
          echo 'LS AZURE INSTANCE'
          ls
          echo 'NODE VERSION'
          docker-compose exec app node --version
          echo 'NPM VERSION'
          docker-compose exec app npm --version
          echo 'PWD:'
          docker-compose exec app pwd
          echo 'LISTING DIR:'
          docker-compose exec app ls
          echo 'TRYING TO PRINT DELTA-TABLE JARS FILES'
          docker-compose exec app ls delta-table/node/jars
          echo 'exporting CLASSPATH'
          echo 'CLASSPATH OUTPUT:'
          docker-compose exec app sh -c 'export CLASSPATH="$(ls /usr/src/app/delta-table/node/jars/*|xargs|sed -e "s/ /,/g")" && echo $CLASSPATH'
          echo 'REMOVING NODE MODULES'
          docker-compose exec app rm -rf node_modules
          echo 'REBUILDING WITH NODE-GYP'
          docker-compose exec app npm rebuild node-gyp
          echo 'REMOVING SYMLINK'
          rm -rf /usr/src/app/node_modules/java/build/node_gyp_bins/python3
          echo 'INSTALLING NPM PACKAGES'
          docker-compose exec app npm install
          echo 'RUNNING TESTS'
          docker-compose exec app sh -c 'export CLASSPATH="$(ls /usr/src/app/delta-table/node/jars/*|xargs|sed -e "s/ /,/g")" && echo $CLASSPATH && npm run test src/__tests__/query.test.ts'

      - name: Tear Down
        if: always()
        run: |
          docker-compose down
